// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservAr.Data;

#nullable disable

namespace ReservAr.Migrations
{
    [DbContext(typeof(ReservArDbContext))]
    [Migration("20260429012242_AddSeatUniqueIndex")]
    partial class AddSeatUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservAr.Models.Audit_Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("character varying(6000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Audit_Log", (string)null);
                });

            modelBuilder.Entity("ReservAr.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.ToTable("Event", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 6, 16, 21, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Noche de Rock Amateur",
                            Status = "DISPONIBLE",
                            Venue = "Niceto Club - CABA"
                        });
                });

            modelBuilder.Entity("ReservAr.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReservedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("ReservAr.Models.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("SectorId", "RowIdentifier", "SeatNumber")
                        .IsUnique();

                    b.ToTable("Seat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            RowIdentifier = "B",
                            SeatNumber = 11,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            RowIdentifier = "B",
                            SeatNumber = 12,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            RowIdentifier = "B",
                            SeatNumber = 13,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            RowIdentifier = "B",
                            SeatNumber = 14,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            RowIdentifier = "B",
                            SeatNumber = 15,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            RowIdentifier = "B",
                            SeatNumber = 16,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            RowIdentifier = "B",
                            SeatNumber = 17,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            RowIdentifier = "B",
                            SeatNumber = 18,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            RowIdentifier = "B",
                            SeatNumber = 19,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            RowIdentifier = "B",
                            SeatNumber = 20,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            RowIdentifier = "C",
                            SeatNumber = 21,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            RowIdentifier = "C",
                            SeatNumber = 22,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            RowIdentifier = "C",
                            SeatNumber = 23,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            RowIdentifier = "C",
                            SeatNumber = 24,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            RowIdentifier = "C",
                            SeatNumber = 25,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            RowIdentifier = "C",
                            SeatNumber = 26,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            RowIdentifier = "C",
                            SeatNumber = 27,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            RowIdentifier = "C",
                            SeatNumber = 28,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            RowIdentifier = "C",
                            SeatNumber = 29,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            RowIdentifier = "C",
                            SeatNumber = 30,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            RowIdentifier = "D",
                            SeatNumber = 31,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            RowIdentifier = "D",
                            SeatNumber = 32,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            RowIdentifier = "D",
                            SeatNumber = 33,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            RowIdentifier = "D",
                            SeatNumber = 34,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            RowIdentifier = "D",
                            SeatNumber = 35,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            RowIdentifier = "D",
                            SeatNumber = 36,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            RowIdentifier = "D",
                            SeatNumber = 37,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            RowIdentifier = "D",
                            SeatNumber = 38,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            RowIdentifier = "D",
                            SeatNumber = 39,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            RowIdentifier = "D",
                            SeatNumber = 40,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            RowIdentifier = "E",
                            SeatNumber = 41,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            RowIdentifier = "E",
                            SeatNumber = 42,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            RowIdentifier = "E",
                            SeatNumber = 43,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            RowIdentifier = "E",
                            SeatNumber = 44,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            RowIdentifier = "E",
                            SeatNumber = 45,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            RowIdentifier = "E",
                            SeatNumber = 46,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            RowIdentifier = "E",
                            SeatNumber = 47,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            RowIdentifier = "E",
                            SeatNumber = 48,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            RowIdentifier = "E",
                            SeatNumber = 49,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            RowIdentifier = "E",
                            SeatNumber = 50,
                            SectorId = 1,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000052"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000053"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000054"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000055"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000056"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000057"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000058"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000059"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000060"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000061"),
                            RowIdentifier = "B",
                            SeatNumber = 11,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000062"),
                            RowIdentifier = "B",
                            SeatNumber = 12,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000063"),
                            RowIdentifier = "B",
                            SeatNumber = 13,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000064"),
                            RowIdentifier = "B",
                            SeatNumber = 14,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000065"),
                            RowIdentifier = "B",
                            SeatNumber = 15,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000066"),
                            RowIdentifier = "B",
                            SeatNumber = 16,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000067"),
                            RowIdentifier = "B",
                            SeatNumber = 17,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000068"),
                            RowIdentifier = "B",
                            SeatNumber = 18,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000069"),
                            RowIdentifier = "B",
                            SeatNumber = 19,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000070"),
                            RowIdentifier = "B",
                            SeatNumber = 20,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000071"),
                            RowIdentifier = "C",
                            SeatNumber = 21,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000072"),
                            RowIdentifier = "C",
                            SeatNumber = 22,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000073"),
                            RowIdentifier = "C",
                            SeatNumber = 23,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000074"),
                            RowIdentifier = "C",
                            SeatNumber = 24,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000075"),
                            RowIdentifier = "C",
                            SeatNumber = 25,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000076"),
                            RowIdentifier = "C",
                            SeatNumber = 26,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000077"),
                            RowIdentifier = "C",
                            SeatNumber = 27,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000078"),
                            RowIdentifier = "C",
                            SeatNumber = 28,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000079"),
                            RowIdentifier = "C",
                            SeatNumber = 29,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000080"),
                            RowIdentifier = "C",
                            SeatNumber = 30,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000081"),
                            RowIdentifier = "D",
                            SeatNumber = 31,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000082"),
                            RowIdentifier = "D",
                            SeatNumber = 32,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000083"),
                            RowIdentifier = "D",
                            SeatNumber = 33,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000084"),
                            RowIdentifier = "D",
                            SeatNumber = 34,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000085"),
                            RowIdentifier = "D",
                            SeatNumber = 35,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000086"),
                            RowIdentifier = "D",
                            SeatNumber = 36,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000087"),
                            RowIdentifier = "D",
                            SeatNumber = 37,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000088"),
                            RowIdentifier = "D",
                            SeatNumber = 38,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000089"),
                            RowIdentifier = "D",
                            SeatNumber = 39,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000090"),
                            RowIdentifier = "D",
                            SeatNumber = 40,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000091"),
                            RowIdentifier = "E",
                            SeatNumber = 41,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000092"),
                            RowIdentifier = "E",
                            SeatNumber = 42,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000093"),
                            RowIdentifier = "E",
                            SeatNumber = 43,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000094"),
                            RowIdentifier = "E",
                            SeatNumber = 44,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000095"),
                            RowIdentifier = "E",
                            SeatNumber = 45,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000096"),
                            RowIdentifier = "E",
                            SeatNumber = 46,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000097"),
                            RowIdentifier = "E",
                            SeatNumber = 47,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000098"),
                            RowIdentifier = "E",
                            SeatNumber = 48,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000099"),
                            RowIdentifier = "E",
                            SeatNumber = 49,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000100"),
                            RowIdentifier = "E",
                            SeatNumber = 50,
                            SectorId = 2,
                            Status = "Disponible",
                            Version = 0
                        });
                });

            modelBuilder.Entity("ReservAr.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Sector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Platea Alta",
                            Price = 25000.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Platea Baja",
                            Price = 10000.00m
                        });
                });

            modelBuilder.Entity("ReservAr.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ReservAr.Models.Audit_Log", b =>
                {
                    b.HasOne("ReservAr.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReservAr.Models.Reservation", b =>
                {
                    b.HasOne("ReservAr.Models.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservAr.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReservAr.Models.Seat", b =>
                {
                    b.HasOne("ReservAr.Models.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReservAr.Models.Sector", b =>
                {
                    b.HasOne("ReservAr.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
